import { walkPrices } from "./prng";
import type {
  Campaign,
  Pool,
  Position,
  Proposal,
  Token,
  Trade,
  Trader,
} from "./types";

const DAY = 86_400_000;
const HOUR = 3_600_000;
const MIN = 60_000;

function idx<T extends { id: string }>(rows: T[]) {
  return Object.fromEntries(rows.map((r) => [r.id, r]));
}

export function makeSeed(now = Date.now()) {
  const traders: Trader[] = [
    {
      id: "you",
      handle: "you",
      name: "You",
      bio: "Demo desk. Ten thousand in paper USDC. Vote, back, copy.",
      followers: 12,
      following: 4,
      pnlPct: 4.2,
      pnlUsd: 186,
      winRate: 0.5,
      avgHold: "2d",
      thesisCount: 1,
    },
    {
      id: "mira",
      handle: "mira",
      name: "Mira Chen",
      bio: "Collects studios, not tickers. Holds through the quiet weeks.",
      followers: 18420,
      following: 41,
      pnlPct: 86.4,
      pnlUsd: 142300,
      winRate: 0.71,
      avgHold: "18d",
      thesisCount: 22,
    },
    {
      id: "juno",
      handle: "juno",
      name: "Juno",
      bio: "Plays games. Backs the rooms that actually ship builds.",
      followers: 22110,
      following: 88,
      pnlPct: 124.8,
      pnlUsd: 210440,
      winRate: 0.64,
      avgHold: "6d",
      thesisCount: 31,
    },
    {
      id: "kale",
      handle: "kale",
      name: "Kale",
      bio: "Infra only. If it cannot meter a kilowatt, I pass.",
      followers: 9804,
      following: 19,
      pnlPct: 41.2,
      pnlUsd: 56210,
      winRate: 0.68,
      avgHold: "31d",
      thesisCount: 14,
    },
    {
      id: "drift",
      handle: "drift",
      name: "Drift",
      bio: "Flow trader. In on the vote, out when the room gets loud.",
      followers: 30112,
      following: 120,
      pnlPct: 38.9,
      pnlUsd: 88100,
      winRate: 0.58,
      avgHold: "11h",
      thesisCount: 9,
    },
    {
      id: "salt",
      handle: "salt",
      name: "Salt",
      bio: "LP stays in the weir. I vote no on every unlock.",
      followers: 15660,
      following: 7,
      pnlPct: 22.4,
      pnlUsd: 33480,
      winRate: 0.74,
      avgHold: "45d",
      thesisCount: 18,
    },
    {
      id: "nori",
      handle: "nori",
      name: "Nori",
      bio: "Culture desk. Drops, rooms, memberships with a door.",
      followers: 11208,
      following: 64,
      pnlPct: 54.1,
      pnlUsd: 41900,
      winRate: 0.61,
      avgHold: "9d",
      thesisCount: 16,
    },
    {
      id: "ash",
      handle: "ash",
      name: "Ash Vale",
      bio: "Sells the rip. Writes the opposite thesis on purpose.",
      followers: 17890,
      following: 53,
      pnlPct: -8.6,
      pnlUsd: -12440,
      winRate: 0.47,
      avgHold: "4h",
      thesisCount: 27,
    },
    {
      id: "reed",
      handle: "reed",
      name: "Reed",
      bio: "Label economics. Vinyl, rooms, touring float.",
      followers: 6402,
      following: 22,
      pnlPct: 19.8,
      pnlUsd: 12880,
      winRate: 0.66,
      avgHold: "21d",
      thesisCount: 8,
    },
    {
      id: "vesper",
      handle: "vesper",
      name: "Vesper",
      bio: "Writes the long note. Size is small until the vote clears.",
      followers: 8901,
      following: 31,
      pnlPct: 33.0,
      pnlUsd: 22150,
      winRate: 0.69,
      avgHold: "14d",
      thesisCount: 40,
    },
    {
      id: "oak",
      handle: "oak",
      name: "Oak",
      bio: "Utility maxi. Membership must do a job in the real room.",
      followers: 4308,
      following: 14,
      pnlPct: 12.7,
      pnlUsd: 8040,
      winRate: 0.72,
      avgHold: "52d",
      thesisCount: 6,
    },
    {
      id: "pix",
      handle: "pix",
      name: "Pix",
      bio: "First fill on new campaigns. Size clipped. Fast hands.",
      followers: 25940,
      following: 201,
      pnlPct: 210.5,
      pnlUsd: 330200,
      winRate: 0.55,
      avgHold: "9h",
      thesisCount: 4,
    },
  ];

  const tokens: Token[] = [
    {
      id: "aether",
      ticker: "AETHER",
      name: "Aether Atelier",
      pitch:
        "Membership for a generative studio. Holders get edition rights, hanging slots, and a cut of secondary.",
      category: "art",
      creatorId: "mira",
      status: "live",
      supply: 1_000_000,
      price: 0.172,
      volume24h: 48200,
      holders: 1264,
      history: walkPrices(0.172, 48, 11, 0.08),
      lpLocked: true,
      createdAt: now - 21 * DAY,
    },
    {
      id: "nova",
      ticker: "NOVA",
      name: "Nova Room",
      pitch:
        "Revenue share for an independent game studio shipping a third-person climber this winter.",
      category: "startup",
      creatorId: "juno",
      status: "raising",
      supply: 1_000_000,
      price: 0.1,
      volume24h: 0,
      holders: 186,
      history: walkPrices(0.1, 16, 22, 0.02),
      lpLocked: true,
      createdAt: now - 4 * DAY,
    },
    {
      id: "grid",
      ticker: "GRID",
      name: "Grid Co-op",
      pitch:
        "Neighborhood solar credits. Token is a claim on a 40-roof cooperative already metering.",
      category: "utility",
      creatorId: "kale",
      status: "live",
      supply: 1_000_000,
      price: 0.1025,
      volume24h: 22140,
      holders: 840,
      history: walkPrices(0.1025, 48, 33, 0.045),
      lpLocked: true,
      createdAt: now - 34 * DAY,
    },
    {
      id: "vinyl",
      ticker: "VINYL",
      name: "Vinyl Commons",
      pitch:
        "A pressing plant and label desk. Holders vote the seasonal run and take wholesale on the first 2k jackets.",
      category: "art",
      creatorId: "reed",
      status: "proposed",
      supply: 1_000_000,
      price: 0,
      volume24h: 0,
      holders: 0,
      history: [],
      lpLocked: true,
      createdAt: now - 2 * DAY,
    },
    {
      id: "thread",
      ticker: "THREAD",
      name: "Thread Atelier",
      pitch:
        "Drop-rights for a four-person pattern studio. Token is the door to sample sales and archive licenses.",
      category: "art",
      creatorId: "nori",
      status: "live",
      supply: 1_000_000,
      price: 0.0786,
      volume24h: 17440,
      holders: 602,
      history: walkPrices(0.0786, 48, 44, 0.07),
      lpLocked: true,
      createdAt: now - 16 * DAY,
    },
    {
      id: "lumen",
      ticker: "LUMEN",
      name: "Lumen Lab",
      pitch:
        "Open-source large-format camera. Community voted it down — optics bill was under-specified.",
      category: "startup",
      creatorId: "vesper",
      status: "failed",
      supply: 1_000_000,
      price: 0,
      volume24h: 0,
      holders: 0,
      history: [],
      lpLocked: true,
      createdAt: now - 18 * DAY,
    },
    {
      id: "kiln",
      ticker: "KILN",
      name: "Kiln Hall",
      pitch:
        "A shared gas kiln and storefront. Members book firings and split wholesale from the front room.",
      category: "art",
      creatorId: "oak",
      status: "raising",
      supply: 1_000_000,
      price: 0.08,
      volume24h: 0,
      holders: 64,
      history: walkPrices(0.08, 12, 55, 0.015),
      lpLocked: true,
      createdAt: now - 1 * DAY,
    },
    {
      id: "echo",
      ticker: "ECHO",
      name: "Echo Net",
      pitch:
        "Membership for a six-show podcast network. Token gates ad-free feeds and a guest-book vote.",
      category: "utility",
      creatorId: "vesper",
      status: "live",
      supply: 1_000_000,
      price: 0.191,
      volume24h: 61300,
      holders: 1540,
      history: walkPrices(0.191, 48, 66, 0.06),
      lpLocked: true,
      createdAt: now - 40 * DAY,
    },
  ];

  const pools: Record<string, Pool> = {
    aether: { tokenId: "aether", base: 55000, quote: 320000 },
    grid: { tokenId: "grid", base: 41000, quote: 400000 },
    thread: { tokenId: "thread", base: 22000, quote: 280000 },
    echo: { tokenId: "echo", base: 67000, quote: 350000 },
  };

  const proposals: Proposal[] = [
    {
      id: "p-vinyl",
      kind: "campaign",
      tokenId: "vinyl",
      title: "Open the VINYL campaign",
      body: "Reed wants a $36k raise to tool a small pressing line and fund the first seasonal jacket. Community keeps LP. One vote from quorum.",
      creatorId: "reed",
      status: "active",
      endsAt: now + 2 * DAY,
      yesVotes: 99,
      noVotes: 41,
      quorum: 100,
      raiseTarget: 36000,
      raiseDays: 10,
    },
    {
      id: "p-wave",
      kind: "campaign",
      tokenId: "wave",
      title: "Open WAVE — harbor lightkeepers",
      body: "A coastal co-op restoring three automatic lights. Token is a maintenance claim and a night in the keeper house.",
      creatorId: "oak",
      status: "active",
      endsAt: now + 5 * DAY,
      yesVotes: 28,
      noVotes: 11,
      quorum: 80,
      raiseTarget: 18000,
      raiseDays: 14,
    },
    {
      id: "p-lumen",
      kind: "campaign",
      tokenId: "lumen",
      title: "Open the LUMEN campaign",
      body: "Failed. The room wanted a BOM and a foundry quote. Neither landed before the window closed.",
      creatorId: "vesper",
      status: "failed",
      endsAt: now - 12 * DAY,
      yesVotes: 44,
      noVotes: 102,
      quorum: 80,
      raiseTarget: 120000,
      raiseDays: 21,
    },
    {
      id: "p-nova",
      kind: "campaign",
      tokenId: "nova",
      title: "Open the NOVA campaign",
      body: "Passed. Studio posted a vertical slice and a 14-month ship plan. Raise is live.",
      creatorId: "juno",
      status: "executed",
      endsAt: now - 4 * DAY,
      yesVotes: 188,
      noVotes: 37,
      quorum: 80,
      raiseTarget: 50000,
      raiseDays: 12,
    },
    {
      id: "p-echo-lp",
      kind: "futarchy",
      tokenId: "echo",
      title: "Allow ECHO LP to be pulled",
      body: "Community holds the LP. YES buys the right for the network desk to remove liquidity. NO keeps the pool in the weir. Price is the room’s forecast, not a straw poll.",
      creatorId: "salt",
      status: "active",
      endsAt: now + 6 * DAY,
      yesVotes: 0,
      noVotes: 0,
      quorum: 0,
      yesPool: 3800,
      noPool: 6200,
    },
    {
      id: "p-thread-lp",
      kind: "futarchy",
      tokenId: "thread",
      title: "Allow THREAD LP to be pulled",
      body: "Atelier wants seasonal LP so they can re-cut a denim run. Market is leaning YES. Salt is on the other side.",
      creatorId: "nori",
      status: "active",
      endsAt: now + 3 * DAY,
      yesVotes: 0,
      noVotes: 0,
      quorum: 0,
      yesPool: 5700,
      noPool: 4300,
    },
    {
      id: "p-grid-lp",
      kind: "futarchy",
      tokenId: "grid",
      title: "Allow GRID LP to be pulled",
      body: "Resolved. The room paid to keep solar LP locked. Co-op cannot lift the pool.",
      creatorId: "kale",
      status: "executed",
      endsAt: now - 8 * DAY,
      yesVotes: 0,
      noVotes: 0,
      quorum: 0,
      yesPool: 2100,
      noPool: 8900,
    },
  ];

  const campaigns: Campaign[] = [
    {
      id: "c-nova",
      tokenId: "nova",
      proposalId: "p-nova",
      raised: 31200,
      target: 50000,
      backers: 186,
      endsAt: now + 8 * DAY,
      status: "live",
    },
    {
      id: "c-kiln",
      tokenId: "kiln",
      proposalId: "p-kiln",
      raised: 8400,
      target: 25000,
      backers: 64,
      endsAt: now + 11 * DAY,
      status: "live",
    },
  ];

  const theses: Array<[string, string, Trade["side"], number, number, string]> = [
    ["mira", "aether", "buy", 2400, 0.168, "Studio already has a waiting list for the next hanging. Membership is the scarce bit."],
    ["juno", "echo", "buy", 900, 0.188, "Shows are shipping weekly. This is a door, not a meme."],
    ["salt", "grid", "buy", 1600, 0.101, "LP is locked. Yield is a roof, not a chart."],
    ["ash", "thread", "sell", 720, 0.084, "Fashion rooms overfit the drop. I fade the lookbook."],
    ["drift", "aether", "buy", 3100, 0.171, "Vote cleared weeks ago. Flow is still one-way."],
    ["nori", "thread", "buy", 540, 0.076, "I’m on the other side of Ash. Archive licenses actually pay."],
    ["pix", "nova", "buy", 400, 0.1, "Campaign is 62% full. I want the allocation, not the after."],
    ["vesper", "echo", "buy", 1100, 0.19, "Ad-free feed is a dull utility. Dull is the point."],
    ["kale", "grid", "buy", 2200, 0.099, "Meters are real. I sized from last quarter’s kWh, not the pitch."],
    ["oak", "kiln", "buy", 250, 0.08, "Backing the hall. Shared kiln is the whole business."],
    ["reed", "aether", "buy", 300, 0.17, "Art desks that own their LP are rare. Sitting with Mira."],
    ["mira", "thread", "buy", 800, 0.077, "Nori cuts slowly. That’s a compliment."],
    ["juno", "nova", "buy", 2000, 0.1, "It’s my room. Still filling from the same wallet."],
    ["ash", "echo", "sell", 1500, 0.196, "Podcasts do not need a pool this large. Taking the rip."],
    ["drift", "echo", "buy", 2600, 0.189, "Ash selling into a locked LP is the setup."],
    ["salt", "echo", "buy", 1800, 0.192, "Buying NO on the unlock market with this. Hedge is the bag."],
    ["pix", "thread", "buy", 640, 0.078, "First fill leftover. Tiny."],
    ["vesper", "aether", "buy", 450, 0.169, "Long note is in the thesis tab. Size is a round lot."],
  ];

  const trades: Trade[] = theses.map((row, i) => {
    const [traderId, tokenId, side, usd, price, thesis] = row;
    return {
      id: `t${i + 1}`,
      traderId,
      tokenId,
      side,
      usd,
      price,
      thesis,
      ts: now - (18 - i) * 7 * MIN - i * 13_000,
    };
  });

  const positions: Record<string, Position> = {
    aether: { amount: 420, costUsd: 68.4 },
  };

  const waveToken: Token = {
    id: "wave",
    ticker: "WAVE",
    name: "Harbor Lights",
    pitch:
      "Three automatic harbor lights, a keeper house, and a maintenance claim for the channel.",
    category: "utility",
    creatorId: "oak",
    status: "proposed",
    supply: 1_000_000,
    price: 0,
    volume24h: 0,
    holders: 0,
    history: [],
    lpLocked: true,
    createdAt: now - 20 * HOUR,
  };

  return {
    traders: idx(traders),
    tokens: idx([...tokens, waveToken]),
    pools,
    proposals: idx(proposals),
    campaigns: idx(campaigns),
    trades,
    follows: ["mira", "salt", "juno", "kale"],
    userVotes: {} as Record<string, "yes" | "no">,
    futarchyShares: {} as Record<string, { yes: number; no: number }>,
    contributions: {} as Record<string, number>,
    cashUsd: 8420,
    positions,
    seq: 100,
  };
}

export type WeirSnapshot = ReturnType<typeof makeSeed>;
